<section id="galerie" class="galerie">

    <div class="layout-section"></div><!-- filtre de l'image de fond -->

    <div class="galerie-layout">
        <h1><?= $mainTitle ?? "STAR'ISLAND*" ?></h1>
        <h2><?= $h2Title ?? 'Galerie*' ?></h2>


        <img id="main-img" src="./assets/upload/gta_decors2.jpg" alt="image dynamique">
        <small id="caption"></small>
    

        <div id="slider" class="slider" >
            <div class="cascade-slider_container" >
                
                <div class="cascade-slider_slides">

                  <?php foreach($data as $key1 => $array1): ?>
                    <div class="cascade-slider_item "> 
                      <?php // if($array1['title_content'] == 'main title') : ?>  
                            <img src="<?= $array1['name_media']?>"
                                alt="<?= $array1['title_media'] ?>"
                            >  
                      <?php //endif; ?>
                        <!-- <img src="assets/upload/gta_decors4.jpg">       -->

                    </div>
                  <?php endforeach; ?>
                </div>
               
                <div class="arrow-container">

                    <span id="arrowPrev"  class="cascade-slider_arrow cascade-slider_arrow-left" data-action="prev">
                        <!-- <img src="assets/pictures/icons8-chevron-left.png"> -->
                        <i class="fa fa-chevron-left" aria-hidden="true"></i>
                    </span>
                    <span id="arrowNext" class="cascade-slider_arrow cascade-slider_arrow-right" data-action="next">
                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                        <!-- <img src="assets/pictures/icons8-chevron-right.png"> -->
                    </span>
                </div>

            </div>
        </div> <!--end .slider -->
        
    </div>
    
</section>