    <!-- page d'accueil 1ère page -->
    <section class="home">
        <div class="diaporama">
            <div class="elements">
                <div class="element element-home">
                    <img id="home-img" src="<?= $personnage1 ?>" alt="<?= $altPerso1 ?>"> 
                    <div class="layout-section"></div><!-- filtre de l'image de fond -->
                    <div class="caption">
                        <h1><?= $mainTitle ?></h1>
                        <!-- <p id="home-p"></p> -->
                       <p><?= $texte1 ?></p>
                        <i class="fa fa-star" aria-hidden="true"></i>
                    </div>   
                </div>

                <div class="element element-slider">
                    <img id="slider-img" src="<?= $personnage2 ?>" alt="image de fond">
                    <!-- <img id="slider-img" src="assets/pictures/gta_decors6-mob.jpg" alt="image de fond"> -->
                    <div class="layout-section2"></div><!-- filtre de l'image de fond -->
                    <div class="caption">
                        <h1><?= $mainTitle1 ?></h1>
                    </div>  
                    <div id="slider" class="slider" >
                        <div class="cascade-slider_container" >
                            <div class="cascade-slider_slides">
                              <?php foreach($slider_ready as $imgSlider): ?>

                                <div class="cascade-slider_item prev">         
                                    <img src="<?= $imgSlider ?>" alt="image du slider">               
                                </div>
                                
                              <?php endforeach; ?>
                            </div>
                            <div class="arrow-container">
                                <span id="arrowPrev"  class="cascade-slider_arrow cascade-slider_arrow-left" data-action="prev">
                                    <!-- <img src="assets/pictures/icons8-chevron-left.png"> -->
                                    <i class="fa fa-chevron-left" aria-hidden="true"></i>
                                </span>
                                <span id="arrowNext" class="cascade-slider_arrow cascade-slider_arrow-right" data-action="next">
                                    <!-- <img src="assets/pictures/icons8-chevron-right.png"> -->
                                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                </span>
                            </div>
                            
                        </div>
                    </div><!--end .slider -->
                </div>

                <div class="element element-serveur" id="serveur">
                    <img id="serveur-img" src="assets/pictures/gta_decors3-mob.jpg" alt="image de fond">
                    <div class="layout-section"></div><!-- filtre de l'image de fond -->
                    <div class="caption">
                        <h1><?= $mainTitle2 ?></h1>
                    </div> 
                    <form class="home-page3-form" action="">
                        <fieldset>                             
                            <img id="top-serveur" src="assets/pictures/logo-topserveurs.svg" alt="logo top serveurs">              
                            <legend>Star'Island</legend>
                            <div class="etoiles">
                                <i class="fa fa-star home2-star" aria-hidden="true"></i>
                                <i class="fa fa-star home2-star" aria-hidden="true"></i>
                                <i class="fa fa-star home2-star" aria-hidden="true"></i>
                                <i class="fa fa-star home2-star" aria-hidden="true"></i>
                                <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            </div>
                            <input type="hidden" id="home1StarInput" value="3">

                            <div>
                                <textarea name="" id="home2-textarea" rows="2">Ecris ton commentaire ici.</textarea>
                            </div>
                            <button type="submit">Publier</button>
                        </fieldset>
                    </form>
                </div>
            </div>
            <div class="puces">
                <div class="puce-div active" data-item="0"></div>
                <div class="puce-div" data-item="1"></div>
                <div class="puce-div" data-item="2"></div>
            </div>
        </div>

        <!-- <div class="layout-section"></div> -->
    </section>
    <section id="home2" class="home2">
        <div class="home2-container">
            <div class="element">
                <img id="home2-img" src="assets/pictures/gta_decors7-mob.jpg" alt="image de fond">
                <div class="layout-section2"></div>
            </div>
            <div class="home2-avis">
              <?php foreach($data3 as $key => $array): ?>
                <div class="avis" >
                    <!-- <img class="avatar" src="assets/pictures/avatar-homme1.jpg" alt="avatar-profil"> -->
                    <img class="avatar" src="<?= $avatars_ready[$i_avatar] ?>" alt="avatar-profil">
                    <div class="avis-container">
                        <div class="etoiles" data-star="<?= $array['rating_comment'] ?>">
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        </div>
                        <div class="texte">
                            <?= substr($array['text_comment'], 0, 30 ) ?>
                        </div>
                        <?php $date = new DateTime($array['publish_date_comment']); ?>
                        <small>Publié le <?= $date->format('d-m-Y à H:i:s') ?></small>
                    </div>
                </div>
                <?php $i_avatar++ ?>
              <?php endforeach ; ?>

            </div>
            
            <form class="home2-form" action="" method="post">
                <fieldset>                
                    <legend>Ton avis nous intéresse</legend>
                    <div class="etoiles">
                        <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        <i class="fa fa-star home2-star" aria-hidden="true"></i>
                    </div>
                    <input type="hidden" id="home2StarInput" name="rating_comment" value="3">
                    <div>
                        <!-- <label for="nickname_comment">Pseudo</label> -->
                        <input type="text" name="nickname_comment" id="nickname_comment" placeholder="Ton pseudo" value="">
                    </div>
                    <div>
                        <textarea 
                            name="text_comment" 
                            id="home2-textarea" 
                            rows="2"
                            minlength="2"
                            maxlength="127" required>Ecris ton commentaire ici</textarea>
                    </div>
                    <button type="submit">Publier</button>
                </fieldset>
            </form>
        </div>
    </section>
