    <!-- page d'accueil 1ère page -->
    <section class="home">
        <div class="diaporama">
            <div class="elements">
                <div class="element element-home">
                    <img id="home-img" src="assets/pictures/gta_decors1-mob.jpg" alt="photo de la ville"> 
                    <div class="layout-section"></div><!-- filtre de l'image de fond -->
                    <div class="caption">
                        <h1>Bienvenue sur STAR'ISLAND</h1>
                        <!-- <p id="home-p">Relevez des défis passionnants, participez à des courses effrénées et explorez un monde rempli de possibilités infinies. Notre équipe est prête à vous aider et à vous accompagner.  Respectez les règles du serveur, faites preuve de fair-play et préparez-vous à créer des souvenirs inoubliables.</p> -->
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum at, ipsum accusantium doloremque id neque veritatis sint voluptate aliquam? Animi quia eius numquam odit nam. Reprehenderit eligendi vitae ratione error.</p>
                        <i class="fa fa-star" aria-hidden="true"></i>
                    </div>   
                </div>

                <div class="element element-slider">
                    <img id="slider-img" src="assets/pictures/gta_decors6-mob.jpg" alt="image de fond">
                    <div class="layout-section2"></div><!-- filtre de l'image de fond -->
                    <div class="caption">
                        <h1>Bienvenue sur STAR'ISLAND</h1>
                    </div>  
                    <div id="slider" class="slider" >
                        <div class="cascade-slider_container" >

                            <div class="cascade-slider_slides">
                                <div class="cascade-slider_item prev">         
                                    <img src="assets/upload/gta_decors1.jpg">               
                                </div>
                                <div class="cascade-slider_item now">
                                    <img src="assets/upload/gta_decors2.jpg">
                                </div>
                                <div class="cascade-slider_item next">  
                                    <img src="assets/upload/gta_decors3.jpg">  
                                </div>
                                <div class="cascade-slider_item">   
                                    <img src="assets/upload/wallp4.png">
                                </div>
                                <div class="cascade-slider_item ">   
                                    <img src="assets/upload/gta_decors4.jpg">      
                                </div>

                            </div>
                            <div class="arrow-container">
                                <span id="arrowPrev"  class="cascade-slider_arrow cascade-slider_arrow-left" data-action="prev">
                                    <!-- <img src="assets/pictures/icons8-chevron-left.png"> -->
                                    <i class="fa fa-chevron-left" aria-hidden="true"></i>
                                </span>
                                <span id="arrowNext" class="cascade-slider_arrow cascade-slider_arrow-right" data-action="next">
                                    <!-- <img src="assets/pictures/icons8-chevron-right.png"> -->
                                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                </span>
                            </div>
                            
                        </div>
                    </div><!--end .slider -->
                </div>

                <div class="element element-serveur" id="serveur">
                    <img id="serveur-img" src="assets/pictures/gta_decors3-mob.jpg" alt="image de fond">
                    <div class="layout-section"></div><!-- filtre de l'image de fond -->
                    <div class="caption">
                        <h1>Bienvenue sur STAR'ISLAND</h1>
                    </div> 
                    <form class="home-page3-form" action="">
                        <fieldset>                             
                            <img id="top-serveur" src="assets/pictures/logo-topserveurs.svg" alt="logo top serveurs">              
                            <legend>Star'Island</legend>
                            <div class="etoiles">
                                <i class="fa fa-star home2-star" aria-hidden="true"></i>
                                <i class="fa fa-star home2-star" aria-hidden="true"></i>
                                <i class="fa fa-star home2-star" aria-hidden="true"></i>
                                <i class="fa fa-star home2-star" aria-hidden="true"></i>
                                <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            </div>
                            <input type="hidden" id="home1StarInput" value="3">

                            <div>
                                <textarea name="" id="home2-textarea" rows="2">Ecris ton commentaire ici.</textarea>
                            </div>
                            <button type="submit">Publier</button>
                        </fieldset>
                    </form>
                </div>
            </div>
            <div class="puces">
                <div class="puce-div active" data-item="0"></div>
                <div class="puce-div" data-item="1"></div>
                <div class="puce-div" data-item="2"></div>
            </div>
        </div>

        <!-- <div class="layout-section"></div> -->
    </section>
    <section id="home2" class="home2">
        <div class="home2-container">
            <div class="element">
                <img id="home2-img" src="assets/pictures/gta_decors7-mob.jpg" alt="image de fond">
                <div class="layout-section2"></div>
            </div>
            <div class="home2-avis">
              <?php foreach($data as $key => $array): ?>
                <div class="avis" >
                    <img class="avatar" src="assets/pictures/avatar-homme1.jpg" alt="avatar-profil">
                    <div class="avis-container">
                        <div class="etoiles" data-star="<?= $array['rating_comment'] ?>">
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>


                        </div>
                        <div class="texte">
                            <?= substr($array['text_comment'], 0, 30 ) ?>
                        </div>
                        <?php $date = new DateTime($array['publish_date_comment']); ?>
                        <small>Publié le <?= $date->format('d-m-Y à H:i:s') ?></small>
                    </div>
                </div>
              <?php endforeach ; ?>
               
                <!-- <div class="avis" >
                    <img class="avatar" src="assets/pictures/avatar-cochon.jpg" alt="avatar-profil">
                    <div class="avis-container">
                        <div class="etoiles" data-star="2">
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        </div>
                        <div class="texte">
                            Lorem ipsum dolor sit amet consectetur unde.
                        </div>
                    </div>
                </div>
                <div class="avis" >
                    <img class="avatar" src="assets/pictures/avatar-femme1.jpg" alt="avatar-profil">
                    <div class="avis-container">
                        <div class="etoiles" data-star="4">
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                            <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        </div>
                        <div class="texte">
                            Lorem ipsum dolor sit amet consectetur aunde.
                        </div>
                    </div>
                </div> -->
            </div>
            
            <form class="home2-form" action="" method="post">
                <fieldset>                
                    <legend>Ton avis nous intéresse</legend>
                    <div class="etoiles">
                        <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        <i class="fa fa-star home2-star" aria-hidden="true"></i>
                        <i class="fa fa-star home2-star" aria-hidden="true"></i>
                    </div>
                    <input type="hidden" id="home2StarInput" name="rating_comment" value="3">
                    <div>
                        <label for="nickname_comment">Pseudo</label>
                        <input type="text" name="nickname_comment" id="nickname_comment" value="">
                    </div>
                    <div>
                        <textarea 
                            name="text_comment" 
                            id="home2-textarea" 
                            rows="2"
                            minlength="2"
                            maxlength="127" required>Ecris ton commentaire ici</textarea>
                    </div>
                    <button type="submit">Publier</button>
                </fieldset>
            </form>
        </div>
    </section>
    <!-- <script src="assets/js/home.js"></script> -->


     <!-- <div class="avis" >
                    <img class="avatar" src="assets/pictures/avatar-homme4.jpg"  alt="avatar-profil">
                    <div class="avis-container">
                    <div class="etoiles">
                        <img src="assets/pictures/icons8-star-fill.png" alt="avis-star">
                        <img src="assets/pictures/icons8-star-fill.png" alt="avis-star">
                        <img src="assets/pictures/icons8-star-fill.png" alt="avis-star">
                        <img src="assets/pictures/icons8-star-fill.png" alt="avis-star">
                        <img src="assets/pictures/icons8-star-nofill.png" alt="avis-star">

                    </div>
                    <div class="texte">
                        Lorem ipsum dolor sit amet consectetur unde.
                    </div>
                    </div>
                </div> -->