
<section id="team" class="team">
    <div class="layout-section"></div><!-- filtre de l'image de fond -->


    <div class="team-layout">
        <h1>STAR'ISLAND</h1>
        <h2>L'Equipe</h2>

        <nav class="selection">
            <a href="">Tous</a>
            <a href="">Admins</a>
            <a href="">Staff</a>
            <a href="">Devs</a>
            <a href="">Helpers</a>
        </nav>
        <div class="profil_pict">
          <?php $i = 1; foreach( $aDevs as $name => $urlImg): ?>
                <?php //var_dump( count($aDevs) ) ?>
                <?php $i++; ?>
                <!--<div class="raw odd" data-indexraw="1">  .odd even ajoutée en js  -->
            <div class="cell " data-indexProfil="2">  <!-- .cell ajoutée en js -->
                <img class="profil_img" src="<?= $urlImg ?>" alt="">
            
              <?php if(!empty($aSocial[$name])): ?>
                <div class="userSocials">
                <?php foreach( $aSocial[$name] as $reseau => $newurl): ?>
                    <a href="<?= $newurl ?>"class="<?= "social ". $reseau ?>" >
                        <img src="<?= $newurl ?>" alt="<?= "logo ". $reseau  ?>">
                    </a>

                <?php endforeach ?>
                </div>
              <?php endif; ?>
                
                
            </div>
            <div class="empty" data-indexProfil="1"></div>
             
          <?php endforeach; ?>

                <!-- <div class="" data-indexProfil="3"></div>
                <div class="" data-indexProfil="4">
                    <img class="profil_img" src="assets/upload/profil_homme1.jpg" alt="">
                    <div class="description">
                        <p>Giusseppe</p>
                        <a href="">
                            <img id="flip-discord" src="assets/pictures/icons8-discorde.png" alt="">
                        </a>
                    </div>
                </div>
                <div class="" data-indexProfil="5"></div> -->

            <!-- </div> -->
            <!-- <div class="raw " data-indexraw="2">
                <div>
                    <img class="profil_img" src="assets/upload/profil_femme2.jpg" alt="">
                    <div class="description">
                        <p>Mia</p>
                        <a href="">

                            <img id="flip-discord" src="assets/pictures/icons8-discorde.png" alt="">
                        </a>

                    </div>
                </div>
                <div></div>
                <div>
                    <img class="profil_img" src="assets/upload/profil_femme2.jpg" alt="">
                    <div class="description">
                        <p>Mia</p>
                        <a href="">

                            <img id="flip-discord" src="assets/pictures/icons8-discorde.png" alt="">
                        </a>

                    </div>
                </div>
                <div></div>
                <div>
                    <img class="profil_img" src="assets/upload/profil_homme3.jpeg" alt="">
                    <div class="description">
                        <p>Giusseppe</p>
                        <a href="">
                            <img id="flip-discord" src="assets/pictures/icons8-discorde.png" alt="">
                        </a>
                    </div>

                </div>
            </div>-->
            <!-- <div class="raw odd" data-indexraw="1">  

                <div class="" data-indexProfil="1"></div>

                <div class="cell " data-indexProfil="2">  
                    <img class="profil_img" src="assets/upload/profil_femme3.jpg" alt="">
                    <div  class="description">
                        <p>Mia</p>
                        <a href="">
                            <img id="flip-discord" src="assets/pictures/icons8-discorde.png" alt="">
                        </a>
                    </div>
                </div>

                <div class="" data-indexProfil="3"></div>
                <div class="" data-indexProfil="4">
                    <img class="profil_img" src="assets/upload/profil_homme4.jpg" alt="">
                    <div class="description">
                        <p>Giusseppe</p>
                        <a href="">
                           <img id="flip-discord" src="assets/pictures/icons8-discorde.png" alt="">
                        </a>
                    </div>
                </div>
                <div class="" data-indexProfil="5"></div>

            </div>
            <div class="raw " data-indexraw="2">
                <div>
                    <img class="profil_img" src="assets/upload/profil_femme4.jpg" alt="">
                    <div class="description">
                        <p>Mia</p>
                        <a href="">
                            <img id="flip-discord" src="assets/pictures/icons8-discorde.png" alt="">
                        </a>
                    </div>
                </div>
                <div></div>
                <div>
                    <img class="profil_img" src="assets/upload/profil_femme5.webp" alt="">
                    <div class="description">
                        <p>Mia</p>
                        <a href="">
                            <img id="flip-discord" src="assets/pictures/icons8-discorde.png" alt="">
                        </a>
                    </div>
                </div>
                <div></div>
                <div>
                    <img class="profil_img" src="assets/upload/profil_homme5.webp" alt="">
                    <div class="description">
                        <p>Giusseppe</p>
                        <a href="">
                            <img id="flip-discord" src="assets/pictures/icons8-discorde.png" alt="">
                        </a>
                    </div>
                </div>
            </div> -->
            <div class="layout_team_selected"></div>
        </div> <!-- end  .profil_pict -->
    </div>
   
</section>


            <!-- <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front" style="background-image: url('assets/pictures/avatar-cochon.jpg');">

                    </div>
                    <div class="flip-card-back">
                        Studio Ghibli, dirigida y creada por Hayaon.
                    </div>
                </div>
            </div> -->

           


