<section class="vip">
    <div class="perso2 none">
        <img src="<?= $personnage2 ?>" alt="<?= $altPerso2 ?>">
    </div>
    <div class="layout-section3"></div><!-- filtre de l'image de fond -->
    <div class="perso1">
        <img src="<?= $personnage1 ?>" alt="<?= $altPerso1 ?>">
    </div>

    <div class="vip-layout">
        <h1><?= $mainTitle ?? "STAR'ISLAND**" ?> </h1>
        <h2><?= $h2Title ?? 'Devenir VIP**' ?></h2>


        <div class="vip-content-1" >
            <h3><?= $h3Title1 ?? 'VIP**' ?></h3>
            <p><?= $texte1 ?? 'VIP**' ?></p> 
        </div> <!--end .content1 -->
        <div class="vip-content-2" >
            <h3><?= $h3Title2 ?? 'VIP**' ?></h3>
            <p><?= $texte2 ?? 'VIP**' ?></p>
           
        </div> <!--end .content2 -->
        
    </div>
   
</section>