<div class="login">
    <form class="mt-5 w-75 mx-auto" method="post" enctype="multipart/form-data">
        <legend class="text-center">Connexion</legend>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email</label>
            <input name="email" 
                type="text" 
                class="form-control" 
                id="exampleInputEmail1" 
                aria-describedby="emailHelp" required>
            <small class="text-danger"><?= $email ?? ""; ?></small>
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Mot de passe</label>
            <input name="password" 
                type="password" 
                class="form-control" 
                id="exampleInputPassword1"
                required>
            <small class="text-danger"><?= $password  ?? ""; ?></small>
        </div>

        <button type="submit" class="btn btn-primary">Connexion</button>
        <div class="retour mt-5">
            <a href="../../index.php?action=home">Retour sur Star'Island</a>
        </div>
    </form>
</div>




