<div class="container-sm">  
    <div class="row">
        <div class="col-12 col-lg-4 ">


            <form class="w-75 mx-auto mt-5 mb-5" action="" method="post" >
                <legend><?= $motif ?></legend>
            
                <div class="form-group">
                    <small class="text-danger">*</small>
                    <label for="title_content">Titre du contenu</label>
                    <select class="form-control" id="title_content" name="title_content">
                    <?php foreach( SELECT_CONTENT_ARRAY as $value ): ?>        
                        <option value="<?= $value?>"
                        <?php if(isset($data1)): ?>
                            <?= ( $value == $data1['title_content'] ) ?'selected' :''; ?>
                        <?php endif; ?>
                        >
                            <?= $value ?>
                        </option>
                    <?php endforeach ; ?>  
                        <small class="text-danger"><?= $error ?? ''; ?></small>
                        <!-- <option value="">Autre</option>       -->
                    </select>
                </div>
                <div class="form-group">
                    <small class="text-danger">*</small>
                    <label for="description_content">Description du contenu</label>
                    <input 
                    id="description_content" 
                    type="text" 
                    name="description_content"
                    class="form-control" 
                    value="<?= $data1['description_content'] ?? '' ?>" 
                    placeholder="Description"
                    aria-describedby="inputHelp">
                    <small class="text-danger"><?= $error1 ?? ''; ?></small>
                </div>   
                <div class="form-group">
                    <label for="id_page">Selectionnez la page</label>
                    <select class="form-control" id="id_page" name="id_page">
                    <?php foreach($dataSelect as $key1 => $array1): ?>        
                        <option value="<?= $array1['id_page'] ?>"
                        <?php if(isset($data1)): ?>
                            <?= ( $array1['id_page'] == $data1['id_page'] ) ?'selected' :''; ?>
                        <?php endif; ?>
                        >
                            <?= $array1['title_page'] ?>
                        </option>
                    <?php endforeach ; ?>  
                        <!-- <option value="">Autre</option>       -->
                    </select>
                </div>

                <input type="hidden" name="id_content" value="<?= $data1['id_content'] ?? '' ?>">       
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </form>
        </div>

        <div class="col-12 col-lg-6">

            <table class="table table-dark table-striped w-75 mx-auto">
                <thead>
                    <tr>
                        <th class="text-center">Titre</th>
                        <th class="text-center">Page</th>
                        <th class="text-center">Description</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($data as $key => $array): ?>        
                    <tr>
                        <td class="text-center"><?= $array['title_content'] ?></td>
                        <td class="text-center">
                            <?php foreach($dataSelect as $key2 => $array2): ?>
                                <?php if( $array2['id_page'] == $array['id_page'] ) : ?>
                                    <?= $array2['title_page']?>
                                <?php endif ; ?>        
                            <?php endforeach ?>
                        </td>
                        <td class="text-center"><?= substr($array['description_content'], 0, 30);   ?></td>
                        <td class="text-center">
                            <a href="<?= '?action=editContent&id='. $array['id_content'].'&back=true' ?>" 
                                class="btn btn-outline-info">
                                <i class="fas fa-pen"></i>
                            </a>
                            <a href="<?= '?action=deleteContent&id='. $array['id_content'].'&back=true' ?>" 
                                onclick="return confirm('Etes-vous sûr')" class="btn btn-outline-danger">
                                <i class="far fa-trash-alt"></i>

                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
 <!-- <div class="form-group">
            <small class="text-danger">*</small>
            <label for="title_content">Titre du contenu</label>
            <input 
            id="title_content" 
            type="text" 
            name="title_content"
            class="form-control" 
            value="<?php // $data1['title_content'] ?? '' ?>" 
            placeholder="Titre"
            aria-describedby="inputHelp">
            <small class="text-danger"><?php // $error ?? ''; ?></small>
        </div>  -->