<div class="container-sm">   
    <div class="row">
        <div class="col-12 col-lg-4 ">
            <form class="w-75 mx-auto mt-5 mb-5" action="" method="post" enctype="multipart/form-data">
                <legend><?= $motif ?></legend>

                <div class="form-group">
                    <small class="text-danger">*</small>
                    <label for="title_content">Titre de l'événement</label>
                    <input 
                        id="title_content" 
                        type="text" 
                        name="title_content"
                        class="form-control" 
                        value="<?= $title_content ?? '' ?>" 
                        placeholder="Titre de l'événement"
                         aria-describedby="inputHelp">
                    <small class="text-danger"><?= $error1 ?? ''; ?></small>
                </div> 
                
                <div class="form-group">
                    <small class="text-danger">*</small>
                    <label for="description_content">Description de l'événement</label>
                    <input 
                        id="description_content" 
                        type="text" 
                        name="description_content"
                        class="form-control" 
                        value="<?= $description_content ?? '' ?>" 

                        placeholder="Description"
                        aria-describedby="inputHelp">
                    <small class="text-danger"><?= $error2 ?? ''; ?></small>
                </div> 


                <div class="form-group">
                    <small class="text-danger">*</small>
                    <label for="start_date_event">Date de début de l'événement</label>
                    <input 
                        id="start_date_event" 
                        type="date" 
                        name="start_date_event"
                        class="form-control" 
                        value="<?= $displayStartD ?? '' ?>"           
                        placeholder="Date de début"
                        aria-describedby="inputHelp">
                    <small class="text-danger"><?php $error3 ?? ''; ?></small>
                </div> 

                <div class="form-group">
                    <small class="text-danger">*</small>
                    <label for="end_date_event">Date de fin de l'événement</label>
                    <input 
                        id="end_date_event" 
                        type="date" 
                        name="end_date_event"
                        class="form-control" 
                        value="<?= $displayEndD ?>"           
                        placeholder="Date de fin"
                        aria-describedby="inputHelp">
                    <small class="text-danger"><?php $error4 ?? ''; ?></small>
                </div>

                <div class="form-group input-group mb-3 div_input_file">
                    <label for="media_file">Choisir une image ( optionnel )</label>
                    <input type="file"
                        id="media_file" name="media_file" class="form-control"
                        accept="image/png, image/jpeg, image/jpg, image/svg">
                    <small class="text-danger"><?php $error ?? ''; ?></small>
                    <img src="<?= $urlImage ?>" 
                        alt="Image choisie" 
                        width="70" height="50" 
                        style="object-fit: cover;border: #7d7070 2px solid;border-radius: 5px; ">

                    <input type="hidden" name="id_media_type" value="16">
                </div>
                <div class="form-group input-group mb-3 div_input_file">
                    <label for="media_file1">Choisir un audio ( optionnel )</label>
                    <input type="file"
                        id="media_file1" name="media_file1" class="form-control"
                        >
                    <small class="text-danger"><?php $error ?? ''; ?></small>
                    <input type="hidden" name="id_media_type1" value="15">
                </div>

                <div class="form-group">
                    <label for="validate_event">Souhaitez-vous valider cet événement ?</label>
                    <input type="checkbox" 
                        id="validate_event" 
                        name="validate_event" 
                        value="<?= $validateEvent ?? '' ?>" 
                        class="form-control select" <?= (isset($validateEvent) && $validateEvent == '1')? 'checked': '' ?>>
                </div>

                <input type="hidden" name="id_event" value="<?= $_GET['id'] ?? '' ?>">       
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </form>

        </div>

        <div class="col-12 col-lg-6 ">
            <table class="table table-dark table-striped w-75 mx-auto">
                <thead>
                    <tr>
                        <th class="text-center">img</th>
                        <th class="text-center">Titre contenu</th>
                        <th class="text-center">Description contenu</th>
                        <th class="text-center">Date de début</th>
                        <th class="text-center">Date de fin</th>
                        <th class="text-center">Activé</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($data as $key => $array): ?>        
                    <tr>
                        <td class="text-center">
                            <img 
                                src="<?= $array['name_media'] ?>" 
                                alt="Image de l'event"
                                width="45"
                                height="30"
                                style="object-fit: cover;border: black 2px solid;border-radius: 5px;"                                
                                >
                        </td>
                        <td class="text-center"><?= $array['title_content'] ?></td>
                        <td class="text-center"><?= substr($array['description_content'],0,35) ?></td>
                        <?php $date = new DateTime( $array['start_date_event'] );
                                        $displayStartD = $date->format('d/m/Y'); ?>           
                        <td class="text-center"><?= $displayStartD ?></td>

                        <?php $date = new DateTime( $array['end_date_event'] );
                                        $displayEndD = $date->format('d/m/Y'); ?> 
                        <td class="text-center"><?= $displayEndD ?></td>
                        <td class="text-center"><?= ($array['validate_event']==0)? '<i class="fas fa-times"></i>' : '<i class="fas fa-check"></i>' ?></td>
                        <td class="text-center">
                            <a href="<?= '?action=editEvent&id='. $array['id_event'] .'&back=true' ?>" 
                                class="btn btn-outline-info">
                                <i class="fas fa-pen"></i>
                            </a>
                            <a href="<?= '?action=deleteEvent&id='. $array['id_event'].'&back=true' ?>" 
                                onclick="return confirm('Etes-vous sûr')" 
                                class="btn btn-outline-danger">
                                <i class="far fa-trash-alt"></i>

                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>

        </div>
    </div>
</div>


  <!-- <div class="form-group">
                    <label for="id_media_type">Selectionnez le type de média</label>
                    <select class="form-control select" id="id_media_type" name="id_media_type">
                    <?php //foreach($dataSelect as $key1 => $array1): ?>
                      <?php // if( $array1['title_media_type']=='image' || $array1['title_media_type']=='audio') : ?>   
                        <option value="<?php //$array1['id_media_type'] ?>"
                            <?php //if(isset( $idMediaType )): ?>   
                            <?php // ( $array1['id_media_type'] == $idMediaType ) ?'selected' :''; ?>
                            <?php // endif; ?>
                        >
                            <?php // $array1['title_media_type'] ?>
                        </option>
                      <?php // endif; ?>
                     <?php // endforeach ; ?>  
                    </select>
                </div> -->