<div class="container-sm">   
    <form class="w-75 mx-auto mt-5 mb-5" action="" method="post" >
        <legend><?= $motif ?></legend>
        <div class="form-group">
            <small class="text-danger">*</small>
            <label for="start_date_event">Date de début de l'événement</label>
            <input 
                id="start_date_event" 
                type="date" 
                name="start_date_event"
                class="form-control" 
                    <?php foreach ($data as $key => $array4) : ?>
                        <?php if (isset($_GET['id']) && $array4['id_event'] == $_GET['id']): ?>

                        <?php $date = new DateTime( $array4['start_date_event'] );
                                $displayStartD = $date->format('Y-m-d'); ?>
                        value="<?= $displayStartD ?>"           
                      <?php endif; ?>
                    <?php endforeach; ?>
                placeholder="Date de début"
                aria-describedby="inputHelp">
            <small class="text-danger"><?php $error ?? ''; ?></small>
        </div> 

        <div class="form-group">
            <small class="text-danger">*</small>
            <label for="end_date_event">Date de fin de l'événement</label>
            <input 
                id="end_date_event" 
                type="date" 
                name="end_date_event"
                class="form-control" 
                <?php foreach ($data as $key => $array4) : ?>
                    <?php if (isset($_GET['id']) && $array4['id_event'] == $_GET['id']): ?>
                        <?php $date = new DateTime( $array4['end_date_event'] );
                                $displayEndD = $date->format('Y-m-d'); ?>
                        value="<?= $displayEndD ?>"           
                    <?php endif; ?>
                <?php endforeach; ?>
                placeholder="Date de fin"
                aria-describedby="inputHelp">
            <small class="text-danger"><?php $error1 ?? ''; ?></small>
        </div> 
        
        <input type="hidden" name="id_event" value="<?= $_GET['id'] ?? '' ?>">       
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>

    <table class="table table-dark table-striped w-75 mx-auto">
        <thead>
            <tr>
                <th class="text-center">Date de début</th>
                <th class="text-center">Date de fin</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
          <?php foreach($data as $key => $array): ?>        
            <tr>
                <?php $date = new DateTime( $array['start_date_event'] );
                                $displayStartD = $date->format('d/m/Y'); ?>           
                <td class="text-center"><?= $displayStartD ?></td>

                <?php $date = new DateTime( $array['end_date_event'] );
                                $displayEndD = $date->format('d/m/Y'); ?> 
                <td class="text-center"><?= $displayEndD ?></td>
                <td class="text-center">
                    <a href="<?= '?action=editEvent&id='. $array['id_event'] .'&back=true' ?>" 
                        class="btn btn-outline-info">
                        Modifier
                    </a>
                    <a href="<?= '?action=deleteEvent&id='. $array['id_event'].'&back=true' ?>" 
                        onclick="return confirm('Etes-vous sûr')" 
                        class="btn btn-outline-danger">
                        Supprimer
                    </a>
                </td>
            </tr>
          <?php endforeach ?>
        </tbody>
    </table>

</div>