<div class="container-sm">   
    <form class="w-75 mx-auto mt-5 mb-5" action="" method="post" >
        <legend><?= $motif ?></legend>
        <div class="form-group">
            <small class="text-danger">*</small>
            <label for="media_type">Nom du type de média</label>
            <input 
            id="media_type" 
            type="text" 
            name="title_media_type"
            class="form-control" 
            value="<?= $data1['title_media_type'] ?? '' ?>" 
            placeholder="Nom du type de média"
            aria-describedby="inputHelp">
            <small class="text-danger"><?php $error ?? ''; ?></small>
        </div> 
        <input type="hidden" name="id_media_type" value="<?= $data1['id_media_type'] ?? '' ?>">       
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>

    <table class="table table-dark table-striped w-75 mx-auto">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
          <?php foreach($data as $key => $array): ?>        
            <tr>
                <td class="text-center"><?= $array['title_media_type'] ?></td>
                <td class="text-center">
                    <a href="<?= '?action=editMediaType&id='. $array['id_media_type'] ?>" 
                        class="btn btn-outline-info">
                        Modifier
                    </a>
                    <a href="<?= '?action=deleteMediaType&id='. $array['id_media_type'].'&back=true' ?>" 
                        onclick="return confirm('Etes-vous sûr')" class="btn btn-outline-danger">
                        Supprimer
                    </a>
                </td>
            </tr>
          <?php endforeach ?>
        </tbody>
    </table>

</div>