<div class="container-sm">   
    <form class="w-75 mx-auto mt-5 mb-5" action="" method="post" >
        <legend><?= $motif ?></legend>
        <div class="form-group">
            <small class="text-danger">*</small>
            <label for="media_type">Titre de la page</label>
            <input 
                id="title_page" 
                type="text" 
                name="title_page"
                class="form-control" 
                value="<?= $data1['title_page'] ?? '' ?>" 
                placeholder="Nom du type de média"
                aria-describedby="inputHelp">
            <small class="text-danger"><?php $error ?? ''; ?></small>
        </div> 
        <input type="hidden" name="id_page" value="<?= $data1['id_page'] ?? '' ?>">       
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>

    <table class="table table-dark table-striped w-75 mx-auto">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
          <?php foreach($data as $key => $array): ?>        
            <tr>
                <td class="text-center"><?= $array['title_page'] ?></td>
                <td class="text-center">
                    <a href="<?= '?action=editPage&id='. $array['id_page'] .'&back=true' ?>" 
                        class="btn btn-outline-info">
                        Modifier
                    </a>
                    <a href="<?= '?action=deletePage&id='. $array['id_page'].'&back=true' ?>" 
                        onclick="return confirm('Etes-vous sûr')" 
                        class="btn btn-outline-danger">
                        Supprimer
                    </a>
                </td>
            </tr>
          <?php endforeach ?>
        </tbody>
    </table>

</div>