<div class="container-sm">   
    <form class="w-75 mx-auto mt-5 mb-5" action="" method="post" >
        <legend><?= $motif ?></legend>

        <div class="form-group">
            <small class="text-danger">*</small>
            <label for="nickname_team">Pseudo</label>
            <input 
                id="nickname_team" 
                type="text" 
                name="nickname_team"
                class="form-control" 
                    <?php foreach ($data as $key => $array4) : ?>
                        <?php if (isset($_GET['id']) && $array4['id_team'] == $_GET['id']): ?>
                            value="<?= $array4['nickname_team'] ?>"           
                        <?php endif; ?>
                    <?php endforeach; ?>
                placeholder="Pseudo du collègue"
                aria-describedby="inputHelp">
            <small class="text-danger"><?php $error ?? ''; ?></small>
        </div> 

        <div class="form-group">
            <small class="text-danger">*</small>
            <label for="role_team">Rôle</label>
            <input 
                id="role_team" 
                type="text" 
                name="role_team"
                class="form-control" 
                <?php foreach ($data as $key => $array4) : ?>
                    <?php if (isset($_GET['id']) && $array4['id_team'] == $_GET['id']): ?>
                        value="<?= $array4['role_team'] ?>"           
                    <?php endif; ?>
                <?php endforeach; ?>
                placeholder="Rôle"
                aria-describedby="inputHelp">
            <small class="text-danger"><?php $error1 ?? ''; ?></small>
        </div> 
        
        <input type="hidden" name="id_team" value="<?= $_GET['id'] ?? '' ?>">       
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>

    <table class="table table-dark table-striped w-75 mx-auto">
        <thead>
            <tr>
                <th class="text-center">Pseudo</th>
                <th class="text-center">Role</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
          <?php foreach($data as $key => $array): ?>        
            <tr>
                <td class="text-center"><?= $array['nickname_team'] ?></td>
                <td class="text-center"><?= $array['role_team'] ?></td>
                <td class="text-center">
                    <a href="<?= '?action=editTeam&id='. $array['id_team'] .'&back=true' ?>" 
                        class="btn btn-outline-info">
                        Modifier
                    </a>
                    <a href="<?= '?action=deleteTeam&id='. $array['id_team'].'&back=true' ?>" 
                        onclick="return confirm('Etes-vous sûr')" 
                        class="btn btn-outline-danger">
                        Supprimer
                    </a>
                </td>
            </tr>
          <?php endforeach ?>
        </tbody>
    </table>

</div>