<div class="container-sm">   
    <div class="row">
        <div class="col-12 col-lg-4 ">
            <div class="img_profil">
                <img 
                    src="<?= $urlImg ?? '' ?>" 
                    alt="<?= $titleMedia ?? 'avatar' ?>"
                    width="70" height="70"
                    style="object-fit: cover; border-radius: 50%;">
            </div>

            <form class="mx-auto mt-5 mb-5" 
                action="" 
                method="post" 
                enctype="multipart/form-data" >
                <legend><?= $motif ?></legend>

                <div class="form-group">
                    <small class="text-danger">*</small>
                    <label for="nickname_team">Pseudo</label>
                    <input 
                        id="nickname_team" 
                        type="text" 
                        name="nickname_team"
                        class="form-control" 
                            <?php foreach ($data as $key => $array4) : ?>
                                <?php if (isset($_GET['id']) && $array4['id_team'] == $_GET['id']): ?>
                                    value="<?= $array4['nickname_team'] ?>"           
                                <?php endif; ?>
                            <?php endforeach; ?>
                        placeholder="Pseudo du collègue"
                        aria-describedby="inputHelp">
                    <small class="text-danger"><?= $error ?? ''; ?></small>
                </div> 

                <div class="form-group">
                    <small class="text-danger">*</small>
                    <label for="role_team">Rôle</label>
                    <input 
                        id="role_team" 
                        type="text" 
                        name="role_team"
                        class="form-control" 
                        <?php foreach ($data as $key => $array4) : ?>
                            <?php if (isset($_GET['id']) && $array4['id_team'] == $_GET['id']): ?>
                                value="<?= $array4['role_team'] ?>"           
                            <?php endif; ?>
                        <?php endforeach; ?>
                        placeholder="Rôle"
                        aria-describedby="inputHelp">
                    <small class="text-danger"><?= $error2 ?? ''; ?></small>
                </div> 
                
                <div class="form-group input-group mb-3 div_input_file">
                    <small class="text-danger">*</small>
                    <label for="media_file"><?= $input_avatar ?></label>
                    <input type="file"
                        id="media_file" 
                        name="media_file"
                        class="form-control"                       
                        >
                    <small class="text-danger"><?= $error3 ?? ''; ?></small>
                </div>

                <div class="form-group">
                    <input 
                        id="github_team_media" 
                        type="url" 
                        name="github_team_media"
                        class="form-control"                    
                                value="<?= $github ?? '' ?>"                  
                        placeholder="lien github"
                        aria-describedby="inputHelp">
                    <input type="hidden" name="githubId" value="<?= $githubId ?? '' ?>">
                </div>
                <div class="form-group">
                    <input 
                        id="discord_team_media" 
                        type="url" 
                        name="discord_team_media"
                        class="form-control" 
                        value="<?= $discord ?? '' ?>"                  
                        placeholder="lien discord"
                        aria-describedby="inputHelp">
                    <small class="text-danger"><?php $error1 ?? ''; ?></small>
                    <input type="hidden" name="discordId" value="<?= $discordId ?? '' ?>">
                </div> 
                <div class="form-group">
                    <!-- <label for="role_team">Rôle</label> -->
                    <input 
                        id="tiktok_team_media" 
                        type="url" 
                        name="tiktok_team_media"
                        class="form-control" 
                        value="<?= $tiktok ?? '' ?>"                  
                        placeholder="lien tiktok"
                        aria-describedby="inputHelp">
                    <small class="text-danger"><?php $error1 ?? ''; ?></small>
                    <input type="hidden" name="tiktokId" value="<?= $tiktokId ?? '' ?>">
                </div> 
                <div class="form-group">
                    <input 
                        id="instagram_team_media" 
                        type="url" 
                        name="instagram_team_media"
                        class="form-control" 
                        value="<?= $instagram ?? '' ?>"                  
                        placeholder="lien instagram"
                        aria-describedby="inputHelp">
                    <small class="text-danger"><?php $error1 ?? ''; ?></small>
                    <input type="hidden" name="instagramId" value="<?= $instagramId ?? '' ?>">
                </div> 
                <div class="form-group">
                    <!-- <label for="role_team">Rôle</label> -->
                    <input 
                        id="facebook_team_media" 
                        type="url" 
                        name="facebook_team_media"
                        class="form-control" 
                        value="<?= $facebook ?? '' ?>"                  
                        placeholder="lien facebook"
                        aria-describedby="inputHelp">
                    <small class="text-danger"><?php $error1 ?? ''; ?></small>
                    <input type="hidden" name="facebookId" value="<?= $facebookId ?? '' ?>">
                </div> 
                <div class="form-group">
                    <!-- <label for="role_team">Rôle</label> -->
                    <input 
                        id="twitter_team_media" 
                        type="url" 
                        name="twitter_team_media"
                        class="form-control" 
                        value="<?= $twitter ?? '' ?>"                  
                        placeholder="lien twitter"
                        aria-describedby="inputHelp">
                    <small class="text-danger"><?php $error1 ?? ''; ?></small>
                    <input type="hidden" name="twitterId" value="<?= $twitterId ?? '' ?>">
                </div> 
                
                <input type="hidden" name="id_team" value="<?= $_GET['id'] ?? '' ?>">       
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </form>
        </div>
        <div class="col-12 col-lg-6 ">

            <table class="table table-dark table-striped mx-auto">
                <thead>
                    <tr>
                        <th class="text-center">Pseudo</th>
                        <th class="text-center">Role</th>
                        <th class="text-center" >titre media</th>
                        <th class="text-center" >Url media</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
              <?php if(!empty($data1)) : ?>
                <?php foreach($data1 as $key => $array): ?> 
                    <?php // debug($array); die; ?>       
                    <tr>
                        <td class="text-center"><?= substr($array['nickname_team'],0,30) ?></td>
                        <td class="text-center"><?= substr($array['role_team'],0,30) ?></td>
                        <td class="text-cente "><?= substr($array['title_media'],0,30) ?></i></td>
                        <td class="text-center "><?= substr($array['name_media'],0,30) ?></i></td>
                        <td class="text-center">
                            <a href="<?= '?action=editTeam&id='. $array['id_team'] .'&back=true' ?>" 
                                class="btn btn-outline-info">
                                <i class="fas fa-pen"></i>
                            </a>
                            <a href="<?= '?action=deleteTeam&id='. $array['id_team'].'&back=true' ?>" 
                                onclick="return confirm('Etes-vous sûr')" 
                                class="btn btn-outline-danger">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
              <?php endif ; ?>
                </tbody>
            </table>
        </div>

    </div>
</div>