    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul 
            class="navbar-nav  text-white sidebar sidebar-dark accordion" 
            id="accordionSidebar" 
            style="background-color: #000000;"
            >
            <!-- Sidebar - Brand -->
            <a 
                class="sidebar-brand d-flex align-items-center justify-content-center" 
                href="<?= BASE_PATH ; ?>"
                >
                <div class="sidebar-brand-icon">
                    <!-- <i class="fas fa-laugh"></i> -->
                    <img src="<?= BASE_PATH . 'assets/pictures/logo_starIsl.png' ?>" alt="logo" width="40">
                </div>
                <div class="sidebar-brand-text mx-3">
                    <sup>Admin</sup>
                </div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
                <!-- Nav Item - Dashboard -->
                <!-- Divider -->
            <hr class="sidebar-divider">
                <!-- Heading -->
            <div class="sidebar-heading">
                gestion
            </div>

            <hr class="sidebar-divider">
            <li class="nav-item listMedia " >
                <a class="nav-link collapsed" 
                   href="<?= BASE_PATH . '?action=listMedia&back=true' ?>" 
                   style="<?= ($action=='listMedia' )?'color:#ea4c6f;' : '' ?>">
                    <i class="fas fa-fw fa-wrench" style="<?= ($action=='listMedia' )?'color:#ea4c6f;' : '' ?>"></i>
                    <span>Gestion médias</span>
                </a>
            </li>

            <hr class="sidebar-divider d-none d-md-block">
            <li class="nav-item">
                <a class="nav-link collapsed" 
                   href="<?= BASE_PATH . '?action=media_type&back=true' ?>" 
                   style="<?= ($action=='media_type' )?'color:#ea4c6f;' : '' ?>">
                    <i class="fas fa-fw fa-wrench" style="<?= ($action=='media_type' )?'color:#ea4c6f;' : '' ?>"></i>
                    <span>Gestion type de médias</span>
                </a>
            </li>


            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed" 
                   href="<?= BASE_PATH . '?action=listPage&back=true' ?>" 
                   style="<?= ($action=='listPage' )?'color:#ea4c6f;' : '' ?>" >
                    <i class="fas fa-fw fa-wrench" style="<?= ($action=='listPage' )?'color:#ea4c6f;' : '' ?>"></i>
                    <span>Gestion des pages</span>
                </a>
            </li>

            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed" 
                   href="<?= BASE_PATH . '?action=listTeam&back=true' ?>" 
                   style="<?= ($action=='listTeam' )?'color:#ea4c6f;' : '' ?>">
                    <i class="fas fa-fw fa-wrench" style="<?= ($action=='listTeam' )?'color:#ea4c6f;' : '' ?>"></i>
                    <span>Gestion team</span>
                </a>
            </li>


            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed" 
                   href="<?= BASE_PATH . '?action=listContent&back=true' ?>"
                   style="<?= ($action=='listContent' )?'color:#ea4c6f;' : '' ?>">

                    <i class="fas fa-fw fa-wrench" style="<?= ($action=='listContent' )?'color:#ea4c6f;' : '' ?>"></i>
                    <span>Gestion des contenus</span>
                </a>
            </li>


            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed"  
                   href="<?= BASE_PATH . '?action=listComment&back=true' ?>"
                   style="<?= ($action=='listComment' )?'color:#ea4c6f;' : '' ?>">
                    <i class="fas fa-fw fa-wrench" tyle="<?= ($action=='listComment' )?'color:#ea4c6f;' : '' ?>"></i>
                    <span>Gestion commentaires</span>
                </a>
            </li>

            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed" 
                   href="<?= BASE_PATH . '?action=listEvent&back=true' ?>" 
                   style="<?= ($action=='listEvent' )?'color:#ea4c6f;' : '' ?>">
                    <i class="fas fa-fw fa-wrench" style="<?= ($action=='listEvent' )?'color:#ea4c6f;' : '' ?>"></i>
                    <span>Gestion événements</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <!-- Topbar -->
                <nav 
                    class="navbar navbar-expand navbar-light  topbar mb-4 static-top shadow" 
                    style="background-color: #000000;"
                    >

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <li class="connected">
                            <a href="<?=  BASE_PATH.'?action=disconnect&back=true' ; ?>" 
                                class="btn btn-danger mt-3" >
                                Déconnexion
                            </a>
                        </li>

                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link " href="<?= BASE_PATH; ?>" role="button">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Voir le site</span>
                                <img class="img-profile rounded-circle"
                                    src="">
                            </a>

                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->
                <div class="container col-3 ">
                    <div class="alert  text-center">

                    </div>
                </div>


                <div class="container-fluid">

                    <?php if (isset($_SESSION['message'])) :  ?>
                        <?php foreach ($_SESSION['message'] as $type => $message) : ?>
                            <?php //var_dump( $message); die(); ?>
                            <?php //foreach ($messages as $message) : ?>
                                <div class=" w-25 rounded text-center ml-5 alert alert-<?= $type ?>">
                                    <h3><?= $message ?></h3>
                                </div>
                            <?php // endforeach; ?>
                        <?php endforeach; ?>
                        <?php unset($_SESSION['message']); ?>
                    <?php endif; ?>
                    <!-- Page Heading -->

                    <?php include "back/".$content.".phtml" ?>

                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of #content -->

        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End #wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <script src="assets/jquery/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/jquery-easing/jquery.easing.min.js"></script>
    <script src="assets/js/sb-admin-2.min.js"></script>
    <script src="assets/js/controllers_js/controllers.js"></script>
    <?php if (isset( $js)) : ?>
        <script src="<?= $js ?>"></script>
    <?php endif; ?> 

</body>


</html>

