    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul 
            class="navbar-nav  text-white sidebar sidebar-dark accordion" 
            id="accordionSidebar" 
            style="background-color: #000000;"
            >
            <!-- Sidebar - Brand -->
            <a 
                class="sidebar-brand d-flex align-items-center justify-content-center" 
                href="<?= BASE_PATH .'back/'; ?>"
                >
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh"></i>
                </div>
                <div class="sidebar-brand-text mx-3"><?= CONFIG['app']['name']. " Admin**" ?></sup></div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
                <!-- Nav Item - Dashboard -->
                <!-- Divider -->
            <hr class="sidebar-divider">
                <!-- Heading -->
            <div class="sidebar-heading">
                gestion
            </div>

            <hr class="sidebar-divider">
            <li class="nav-item listMedia " <?= ($action == 'listMedia')? "style='color:pink;'" : '' ; ?> >
                <a class="nav-link collapsed" href="<?= BASE_PATH . '?action=listMedia&back=true' ?>" >
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Gestion médias</span>
                </a>
            </li>

            <hr class="sidebar-divider d-none d-md-block">
            <li class="nav-item">
                <a class="nav-link collapsed" href="<?= BASE_PATH . '?action=media_type&back=true' ?>" >
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Gestion type de médias</span>
                </a>
            </li>


            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed" href="<?= BASE_PATH . '?action=listPage&back=true' ?>" >
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Gestion des pages</span>
                </a>
            </li>

            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed" href="<?= BASE_PATH . '?action=listTeam&back=true' ?>" >
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Gestion team</span>
                </a>
            </li>


            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed" href="<?= BASE_PATH . '?action=listContent&back=true' ?>">

                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Gestion des contenus</span>
                </a>
            </li>


            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed"  href="<?= BASE_PATH . '?action=listComment&back=true' ?>">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Gestion commentaires</span>
                </a>
            </li>

            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed" href="<?= BASE_PATH . '?action=listEvent&back=true' ?>" >
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Gestion événements</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav 
                    class="navbar navbar-expand navbar-light  topbar mb-4 static-top shadow" 
                    style="background-color: #000000;"
                    >

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link " href="<?= BASE_PATH; ?>" role="button">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Voir le site</span>
                                <img class="img-profile rounded-circle"
                                    src="">
                            </a>

                        </li>
                        <!-- <li class="nav-item">
                            <a class="nav-link collapsed" 
                                href="<?php //BASE_PATH . '?action=pageList&back=true' ?>" 
                                data-toggle="collapse" data-target="#collapseUtilities"
                                aria-expanded="true" aria-controls="collapseUtilities">
                                <i class="fas fa-fw fa-wrench"></i>
                                <span>Gestion pages</span>
                            </a>
                            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                                data-parent="#accordionSidebar">
                                <div class="bg-white py-2 collapse-inner rounded">
                                    <a class="dropdown-item" 
                                        href="<?php // BASE_PATH . '?action=pageList&back=true' ?>">
                                        Inserer une page
                                    </a>
                                </div>
                            </div>
                            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                                data-parent="#accordionSidebar">
                                <div class="bg-white py-2 collapse-inner rounded">
                                    <a class="dropdown-item" href=""></a>
                                </div>
                            </div>
                        </li> -->
                    </ul>
                </nav>
                <!-- End of Topbar -->
                <div class="container col-3 ">
                    <div class="alert  text-center">

                    </div>
                </div>


                <div class="container-fluid">

                    <?php if (isset($_SESSION['message'])) :  ?>
                        <?php foreach ($_SESSION['message'] as $type => $message) : ?>
                            <?php //var_dump( $message); die(); ?>
                            <?php //foreach ($messages as $message) : ?>
                                <div class=" w-25 rounded text-center ml-5 alert alert-<?= $type ?>">
                                    <h3><?= $message ?></h3>
                                </div>
                            <?php // endforeach; ?>
                        <?php endforeach; ?>
                        <?php unset($_SESSION['message']); ?>
                    <?php endif; ?>
                    <!-- Page Heading -->

                    <?php include "back/".$content.".phtml" ?>

                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of #content -->

        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End #wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <script src="assets/jquery/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/jquery-easing/jquery.easing.min.js"></script>
    <script src="assets/js/sb-admin-2.min.js"></script>
    <script src="assets/js/controllers_js/controllers.js"></script>
    <?php if (isset( $js)) : ?>
        <script src="<?= $js ?>"></script>
    <?php endif; ?> 

</body>


</html>

