
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Star Island</title>
    <link rel="shortcut icon" href="<?= BASE_PATH.'assets/pictures/logo_starIsl.ico' ?>" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.2.3/lux/bootstrap.min.css" integrity="sha512-+TCHrZDlJaieLxYGAxpR5QgMae/jFXNkrc6sxxYsIVuo/28nknKtf9Qv+J2PqqPXj0vtZo9AKW/SMWXe8i/o6w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="<?= BASE_PATH.'assets/css/style.css' ?>">
    <link rel="stylesheet" href="<?= BASE_PATH.'assets/css/'. $action .'.css' ?>">
    <link rel="stylesheet" href="<?= BASE_PATH.'assets/fontawesome-free/css/all.css' ?>">
    <script src="<?= BASE_PATH . 'assets/js/links.js' ?>" defer></script>
</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= BASE_PATH; ?>">
                <img src="<?= BASE_PATH . 'assets/pictures/logo_starIsl.png' ?>" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <div class="ul-1">
                        <li class="nav-item">
                            <a class="nav-link active" href="<?= BASE_PATH ?>">
                                <img src="<?= BASE_PATH . 'assets/pictures/icons8-home.png' ?>" alt="home">
                                <span class="visually-hidden">(current)</span>
                            </a>
                            
                        </li>
                    
                        <li class="nav-item">
                            <a class="nav-link" href="?action=galerie">GALERIE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="?action=vip">DEVENIR VIP</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="?action=home#serveur">SERVEUR</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="?action=team">L'EQUIPE</a>
                        </li>
                    </div>
                    <div class="ul-2">
                        <li class="nav-item">
                            <a class="nav-link" href="?action=event">Event <i class="far fa-calendar-check"></i></a>
                        </li>                       
                    </div>

                </ul>
            </div>
        </div>
    </nav>
</header>
<main class="">
    <?php if (isset($_SESSION['messages']) && !empty($_SESSION['messages'])): ?>
    <?php foreach ($_SESSION['messages'] as $type=>$messages): ?>
    <?php foreach ($messages as $key=>$message): ?>
    <div class="alert alert-<?=  $type; ?> text-center w-50 mx-auto">
        <p><?= $message; ?></p>
    </div>

    <?php   unset($_SESSION['messages'][$type][$key]);
            endforeach;  endforeach;  endif;           ?>

    

